server.port=8887

spring.datasource.url=jdbc:postgresql://ep-black-flower-a1acxjgg.ap-southeast-1.aws.neon.tech/iskradb?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
#jdbc:mysql://iskradb.onrender.com:3306/iskradb
spring.datasource.username=iskradb_owner
spring.datasource.password=kjzd7ZfQMtW8
spring.jpa.hibernate.ddl-auto=create

#jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ISKRADB}?createDatabaseIfNotExist=true
#spring.datasource.url=jdbc:h2:file:~/iskradb
#org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=1590

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true